# Generated by Django 5.2.6 on 2025-10-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Pages'},
        ),
    ]
