# Generated by Django 5.2.6 on 2025-09-27 12:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_navigation', models.BooleanField(default=True, help_text='Display the navigation header on this page', verbose_name='Show Navigation Bar')),
                ('show_footer', models.BooleanField(default=True, help_text='Display the footer on this page', verbose_name='Show Footer')),
                ('meta_description', models.TextField(blank=True, default='Professional air conditioning installation, repair & maintenance in Klang Valley. 20+ years experience, certified technicians, competitive pricing. Call +6012-652 6665 for free quote.', help_text='Search engine description (250 characters max)', max_length=250)),
                ('meta_keywords', models.CharField(blank=True, default='air conditioning services Klang Valley, aircond repair KL, aircond installation Selangor, aircon maintenance Malaysia, certified aircond technician, Seng Leong Engineering', help_text='Comma-separated keywords for SEO', max_length=500)),
                ('hero_title', models.CharField(default='Your Certified Aircond Supplier in Klang Valley', help_text='Main heading displayed in hero section', max_length=250)),
                ('hero_description', models.TextField(default='We are a certified air conditioning supplier with over 20 years of proven experience. Trusted by residential and commercial clients across Klang Valley area. We offer the lowest pricing without compromising on quality and provide brand-certified systems from all top air conditioner brands. Our solutions guarantee reliability, energy efficiency and long-term value.', help_text='Hero section description text', max_length=800)),
                ('form_title', models.CharField(default='Get Free Air Conditioning Quote', help_text='Title for the contact form', max_length=100)),
                ('form_subtitle', models.CharField(default='Contact us today for professional air conditioning supply in Klang Valley', help_text='Subtitle for the contact form', max_length=200)),
                ('form_whatsapp_number', models.CharField(default='60122992909', help_text='WhatsApp number (without + sign) for form submissions', max_length=20)),
                ('form_whatsapp_message_template', models.TextField(default="Hi! I'm interested in getting a quote for air conditioning service.\n\n*Name:* {name}\n*Email:* {email}\n*Phone:* {phone}\n*Budget:* {budget}\n*Location:* {location}\n*Requirements:* {message}\n\nPlease contact me for a free quote. Thank you!", help_text='WhatsApp message template. Use {name}, {email}, {phone}, {budget}, {location}, {message} as placeholders')),
                ('form_success_message', models.CharField(default='Redirecting to WhatsApp to send your inquiry...', help_text='Success message shown before redirecting to WhatsApp', max_length=300)),
                ('services_title', models.CharField(default='Professional Air Conditioning Supply in Klang Valley', help_text='Main title for services section', max_length=150)),
                ('services_subtitle', models.CharField(default='Certified technicians delivering excellence across Kuala Lumpur, Selangor, and Klang Valley with 20+ years of experience', help_text='Subtitle for services section', max_length=300)),
                ('stats_title', models.CharField(default='Our Track Record Speaks for Itself', help_text='Title for statistics section', max_length=150)),
                ('stats_subtitle', models.CharField(default='Numbers that demonstrate our commitment to excellence and customer satisfaction', help_text='Subtitle for statistics section', max_length=300)),
                ('partners_title', models.CharField(default='Authorized Air Conditioning Brand Partners', help_text='Title for partners section', max_length=150)),
                ('partners_subtitle', models.CharField(default='Official dealer for leading air conditioning brands in Malaysia', help_text='Subtitle for partners section', max_length=300)),
                ('testimonials_title', models.CharField(default='Customer Reviews & Testimonials', help_text='Title for testimonials section', max_length=150)),
                ('testimonials_subtitle', models.CharField(default='Real feedback from satisfied customers across Klang Valley, Selangor, and Kuala Lumpur', help_text='Subtitle for testimonials section', max_length=300)),
                ('testimonials_embed_code', models.TextField(blank=True, default='<div class="elfsight-app-953cfb60-2f8f-445b-92f9-9380097ebe47" data-elfsight-app-lazy></div>', help_text='Elfsight or other testimonials widget embed code')),
                ('company_name', models.CharField(default='Seng Leong Engineering Sdn Bhd', help_text='Company name', max_length=100)),
                ('phone_primary', models.CharField(default='+6012-652 6665', help_text='Primary phone number', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, default='+6017-510 6665', help_text='Secondary phone number (optional)', max_length=20)),
                ('address_street', models.CharField(default='31, Jalan Bendahara 2, Taman Sejati', help_text='Street address', max_length=200)),
                ('address_city', models.CharField(default='Klang', help_text='City', max_length=50)),
                ('address_state', models.CharField(default='Selangor', help_text='State', max_length=50)),
                ('address_postcode', models.CharField(default='41200', help_text='Postal code', max_length=10)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/sengleongaircond', help_text='Facebook page URL')),
                ('whatsapp_number', models.CharField(default='60122992909', help_text='WhatsApp number (without + sign)', max_length=20)),
                ('whatsapp_message', models.CharField(default='Hi, I would like to get a quote for air conditioning service', help_text='Default WhatsApp message', max_length=200)),
                ('google_maps_embed', models.TextField(default='<iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=31,%20Jalan%20Bendahara%202,%20taman%20sejati,%2041200%20Klang,%20Selangor+(Seng%20Leong%20Engineering%20Sdn%20Bhd)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>', help_text='Google Maps embed code')),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('avatar_color', models.CharField(choices=[('#e91e63', 'Pink'), ('#ff5722', 'Deep Orange'), ('#795548', 'Brown'), ('#607d8b', 'Blue Grey'), ('#9c27b0', 'Purple'), ('#3f51b5', 'Indigo'), ('#2196f3', 'Blue'), ('#009688', 'Teal'), ('#4caf50', 'Green'), ('#ff9800', 'Orange'), ('#f44336', 'Red'), ('#673ab7', 'Deep Purple')], default='#e91e63', help_text='Color for the avatar background (used if no profile picture)', max_length=7)),
                ('review_text', models.TextField(help_text="The review content - will be truncated with 'Read more' if too long", max_length=800)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Star rating (1-5)')),
                ('review_source', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('trustpilot', 'Trustpilot'), ('yelp', 'Yelp'), ('website', 'Website')], default='google', help_text='Platform where the review was posted', max_length=20)),
                ('review_date', models.DateTimeField(help_text='Date when the review was posted (leave blank for auto-fill)')),
                ('is_verified', models.BooleanField(default=True, help_text='Show verified badge')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this review (will appear first in slider)')),
                ('profile_picture', models.ForeignKey(blank=True, help_text='Optional profile picture - will be cropped to circle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_reviews', to='home.homepage')),
            ],
            options={
                'ordering': ['-is_featured', '-review_date'],
            },
        ),
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(help_text='Alt text for the brand image', max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_partners', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text="e.g., '3000+', '90%', '4.8+'", max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USPFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(choices=[('fas fa-dollar-sign', 'Dollar Sign'), ('fas fa-certificate', 'Certificate'), ('fas fa-box-open', 'Box Open'), ('fas fa-shield-alt', 'Shield'), ('fas fa-clipboard-check', 'Clipboard Check'), ('fas fa-user-tie', 'User Tie'), ('fas fa-headset', 'Headset'), ('fas fa-truck', 'Truck')], default='fas fa-certificate', help_text='Select an icon for this feature', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='usp_features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
