# Generated by Django 5.2.6 on 2025-09-19 09:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='navigation_bar',
        ),
        migrations.AddField(
            model_name='homepage',
            name='address_city',
            field=models.CharField(default='Klang', help_text='City', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address_postcode',
            field=models.CharField(default='41200', help_text='Postal code', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address_state',
            field=models.CharField(default='Selangor', help_text='State', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address_street',
            field=models.CharField(default='31, Jalan Bendahara 2, Taman Sejati', help_text='Street address', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_name',
            field=models.CharField(default='Seng Leong Engineering Sdn Bhd', help_text='Company name', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/sengleongaircond', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_action_url',
            field=models.URLField(default='https://formsubmit.co/karimazizc@gmail.com', help_text='Form submission URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_subtitle',
            field=models.CharField(default='Contact us today for professional air conditioning supply in Klang Valley', help_text='Subtitle for the contact form', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_title',
            field=models.CharField(default='Get Free Air Conditioning Quote', help_text='Title for the contact form', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_maps_embed',
            field=models.TextField(default='<iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=31,%20Jalan%20Bendahara%202,%20taman%20sejati,%2041200%20Klang,%20Selangor+(Seng%20Leong%20Engineering%20Sdn%20Bhd)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>', help_text='Google Maps embed code'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(default='We are a certified air conditioning supplier with over 20 years of proven experience. Trusted by residential and commercial clients across Klang Valley area. We offer the lowest pricing without compromising on quality and provide brand-certified systems from all top air conditioner brands. Our solutions guarantee reliability, energy efficiency and long-term value.', help_text='Hero section description text', max_length=800),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, default='Professional air conditioning installation, repair & maintenance in Klang Valley. 20+ years experience, certified technicians, competitive pricing. Call +6012-652 6665 for free quote.', help_text='Search engine description (160 characters max)', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, default='air conditioning services Klang Valley, aircond repair KL, aircond installation Selangor, aircon maintenance Malaysia, certified aircond technician, Seng Leong Engineering', help_text='Comma-separated keywords for SEO', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_subtitle',
            field=models.CharField(default='Official dealer for leading air conditioning brands in Malaysia', help_text='Subtitle for partners section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_title',
            field=models.CharField(default='Authorized Air Conditioning Brand Partners', help_text='Title for partners section', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_primary',
            field=models.CharField(default='+6012-652 6665', help_text='Primary phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_secondary',
            field=models.CharField(blank=True, default='+6017-510 6665', help_text='Secondary phone number (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(default='Certified technicians delivering excellence across Kuala Lumpur, Selangor, and Klang Valley with 20+ years of experience', help_text='Subtitle for services section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Professional Air Conditioning Supply in Klang Valley', help_text='Main title for services section', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_footer',
            field=models.BooleanField(default=True, help_text='Display the footer on this page', verbose_name='Show Footer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_navigation',
            field=models.BooleanField(default=True, help_text='Display the navigation header on this page', verbose_name='Show Navigation Bar'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_subtitle',
            field=models.CharField(default='Numbers that demonstrate our commitment to excellence and customer satisfaction', help_text='Subtitle for statistics section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_title',
            field=models.CharField(default='Our Track Record Speaks for Itself', help_text='Title for statistics section', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_embed_code',
            field=models.TextField(blank=True, default='<div class="elfsight-app-953cfb60-2f8f-445b-92f9-9380097ebe47" data-elfsight-app-lazy></div>', help_text='Elfsight or other testimonials widget embed code'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_subtitle',
            field=models.CharField(default='Real feedback from satisfied customers across Klang Valley, Selangor, and Kuala Lumpur', help_text='Subtitle for testimonials section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(default='Customer Reviews & Testimonials', help_text='Title for testimonials section', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_message',
            field=models.CharField(default='Hi, I would like to get a quote for air conditioning service', help_text='Default WhatsApp message', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_number',
            field=models.CharField(default='60122992909', help_text='WhatsApp number (without + sign)', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Your Certified Aircond Supplier in Klang Valley', help_text='Main heading displayed in hero section', max_length=250),
        ),
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(help_text='Alt text for the brand image', max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_partners', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text="e.g., '3000+', '90%', '4.8+'", max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USPFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(default='fas fa-star', help_text="Font Awesome icon class (e.g., 'fas fa-certificate')", max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='usp_features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
