# Generated by Django 5.2.6 on 2025-09-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_embed_code',
        ),
    ]
