# Generated by Django 5.2.6 on 2025-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_testimonials_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='google_widget_enabled',
            field=models.BooleanField(default=True, help_text='Show Google review widget in hero section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_widget_rating',
            field=models.DecimalField(decimal_places=1, default=4.7, help_text='Overall Google rating (e.g., 4.7)', max_digits=2),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_widget_review_count',
            field=models.PositiveIntegerField(default=16892, help_text='Total number of Google reviews'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_widget_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/place/Seng+Leong+Engineering+Sdn+Bhd', help_text='Link to Google Business profile/reviews'),
        ),
    ]
