# Generated by Django 5.2.6 on 2025-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_footer_remove_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, default='Professional air conditioning installation, repair & maintenance in Klang Valley. 20+ years experience, certified technicians, competitive pricing. Call +6012-652 6665 for free quote.', help_text='Search engine description (160 characters max)', max_length=250),
        ),
        migrations.AlterField(
            model_name='uspfeature',
            name='icon_class',
            field=models.CharField(choices=[('fas fa-dollar-sign', 'Dollar Sign'), ('fas fa-certificate', 'Certificate'), ('fas fa-box-open', 'Box Open'), ('fas fa-shield-alt', 'Shield'), ('fas fa-clipboard-check', 'Clipboard Check'), ('fas fa-user-tie', 'User Tie'), ('fas fa-headset', 'Headset'), ('fas fa-truck', 'Truck')], default='fas fa-certificate', help_text='Select an icon for this feature', max_length=100),
        ),
    ]
