# Generated by Django 5.2.6 on 2025-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_google_widget_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='google_widget_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/place/Seng+Leong+Engineering+Sdn+Bhd/data=!4m2!3m1!1s0x0:0x8bf3d80f0f4ec0bc?sa=X&ved=1t:2428&ictx=111', help_text='Link to Google Business profile/reviews'),
        ),
    ]
