# Generated by Django 5.2.6 on 2025-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, default='Professional air conditioning installation, repair & maintenance in Klang Valley. 20+ years experience, certified technicians, competitive pricing. Call +6012-652 6665 for free quote.', help_text='Search engine description (250 characters max)', max_length=250),
        ),
    ]
