# Generated by Django 5.2.6 on 2025-09-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='form_redirect_url',
            field=models.URLField(blank=True, default='', help_text='URL to redirect after form submission (optional)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_success_message',
            field=models.CharField(default='Thank you for your inquiry! We will contact you within 24 hours with your free quote.', help_text='Success message shown after form submission', max_length=300),
        ),
    ]
