# Generated by Django 5.2.6 on 2025-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_google_widget_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='embed_body_code',
            field=models.TextField(blank=True, help_text='Embed any code in <body> (Google Tag manager)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='embed_head_code',
            field=models.TextField(blank=True, help_text='Embed any code in <head> (Google Analytics or Microsoft Clarity)'),
        ),
    ]
