# Generated by Django 5.2.6 on 2025-10-13 08:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_embed_body_code_homepage_embed_head_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_id', models.CharField(choices=[('hero', 'Hero Section'), ('usp-section', 'USP Features Section'), ('expertise-section', 'Statistics/Expertise Section'), ('partners', 'Partners Section'), ('testimonials', 'Google Reviews Section')], help_text='Select which section this represents', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Show/hide this section on the page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('page', 'section_id')},
            },
        ),
    ]
