# Generated by Django 5.2.6 on 2025-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_form_redirect_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='form_action_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_redirect_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_whatsapp_message_template',
            field=models.TextField(default="Hi! I'm interested in getting a quote for air conditioning service.\n\n*Name:* {name}\n*Email:* {email}\n*Phone:* {phone}\n*Budget:* {budget}\n*Location:* {location}\n*Requirements:* {message}\n\nPlease contact me for a free quote. Thank you!", help_text='WhatsApp message template. Use {name}, {email}, {phone}, {budget}, {location}, {message} as placeholders'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_whatsapp_number',
            field=models.CharField(default='60122992909', help_text='WhatsApp number (without + sign) for form submissions', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='form_success_message',
            field=models.CharField(default='Redirecting to WhatsApp to send your inquiry...', help_text='Success message shown before redirecting to WhatsApp', max_length=300),
        ),
    ]
