# Generated by Django 5.2.6 on 2025-10-13 10:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_embed_body_code_homepage_embed_head_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('text', 0), ('richtext', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(default='We are a certified air conditioning supplier with over 20 years of proven experience. Trusted by residential and commercial clients across Klang Valley area. We offer the lowest pricing without compromising on quality and provide brand-certified systems from all top air conditioner brands. Our solutions guarantee reliability, energy efficiency and long-term value.', help_text='Hero section description text', max_length=800),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_id', models.CharField(choices=[('hero', 'Hero Section'), ('usp-section', 'USP Features Section'), ('expertise-section', 'Statistics/Expertise Section'), ('partners', 'Partners Section'), ('testimonials', 'Google Reviews Section')], help_text='Select which section this represents', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Show/hide this section on the page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('page', 'section_id')},
            },
        ),
    ]
