# Generated by Django 5.2.6 on 2025-10-13 08:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(default='We are a certified air conditioning supplier with over 20 years of proven experience. Trusted by residential and commercial clients across Klang Valley area. We offer the lowest pricing without compromising on quality and provide brand-certified systems from all top air conditioner brands. Our solutions guarantee reliability, energy efficiency and long-term value.', help_text='Hero section description text', max_length=800),
        ),
    ]
