# Generated by Django 5.2.6 on 2025-10-24 13:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_content_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='expertise_content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='partners_content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonial_content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='usp_content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('html', 4), ('call_to_action', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#hero', 'Hero Section'), ('#usp-section', 'USP Features Section'), ('#expertise-section', 'Statistics/Expertise Section'), ('#partners', 'Partners Section'), ('#testimonials', 'Google Reviews Section')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#0A1F44', 'primary-navy'), ('#FFFFFF', 'white'), ('#3B82F6', 'sky-blue'), ('#F4F6FA', 'light-gray'), ('#1E293B', 'dark-text'), ('#06B6D4', 'bright-cyan'), ('#1E3A8A', 'dark-navy-hover'), ('#FACC15', 'yellow-highlight')]}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('gray', 'Gray')]}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 5), ('button_redirect', 6), ('background_color', 7), ('text_color', 8)]], {})}, null=True),
        ),
    ]
