# Generated by Django 5.2.6 on 2025-11-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_expertise_content_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='form_default_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', help_text='Default contact method shown when page loads', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_email_recipient',
            field=models.EmailField(default='info@sengleongaircond.com', help_text='Email address to receive form submissions', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_email_success_message',
            field=models.CharField(default='Thank you! Your inquiry has been sent successfully. We will get back to you soon.', help_text='Success message shown after email is sent', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_enable_email',
            field=models.BooleanField(default=True, help_text='Enable email submission option'),
        ),
    ]
