# Generated by Django 5.2.6 on 2025-11-03 07:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_form_default_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='form_success_message',
            new_name='form_whatsapp_success_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_default_method',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_email_recipient',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_email_success_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_enable_email',
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_submission_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp (JavaScript redirect)'), ('email', 'Email (Wagtail form submission)')], default='email', help_text='Choose how form submissions should be handled. WhatsApp will redirect users to WhatsApp with pre-filled message. Email will save submissions and send via Mailtrap.', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address'),
        ),
        migrations.CreateModel(
            name='HomePageFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
