# Generated by Django 5.2.6 on 2025-11-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_form_success_message_homepage_form_whatsapp_success_message_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapier_webhook_url', models.URLField(blank=True, default='https://hooks.zapier.com/hooks/catch/530937/ur7g2ql/', help_text='Zapier webhook URL to send form submissions to. Leave blank to disable Zapier integration.')),
                ('webhook_enabled', models.BooleanField(default=True, help_text='Enable or disable sending data to the webhook')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Webhook Settings',
            },
        ),
    ]
