# Generated by Django 5.2.6 on 2025-11-03 09:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_webhooksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYouPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('thank_you_title', models.CharField(default='Thank You!', help_text='Main title displayed on thank you page', max_length=100)),
                ('thank_you_message', models.TextField(default="Your inquiry has been successfully submitted. We've received your message and will get back to you as soon as possible.", help_text='Main thank you message', max_length=500)),
                ('info_box_title', models.CharField(default='What Happens Next?', help_text='Title for the information box', max_length=100)),
                ('info_box_content', wagtail.fields.RichTextField(default="<p>✓ We'll review your inquiry within 24 hours</p><p>✓ Our team will contact you via email or phone</p><p>✓ We'll provide a detailed quote and answer all your questions</p>", help_text='Rich text content for the information box')),
                ('home_button_text', models.CharField(default='Back to Home', help_text='Text for the home button', max_length=50)),
                ('submit_another_button_text', models.CharField(default='Submit Another Inquiry', help_text='Text for the submit another inquiry button', max_length=50)),
                ('contact_section_title', models.CharField(default='Need Immediate Assistance?', help_text='Title for the contact section', max_length=100)),
                ('phone_link_text', models.CharField(default='Call Us', help_text='Text for the phone link (if different from phone number)', max_length=50)),
                ('whatsapp_link_text', models.CharField(default='WhatsApp Us', help_text='Text for the WhatsApp link', max_length=50)),
                ('show_info_box', models.BooleanField(default=True, help_text='Show the information box on thank you page')),
                ('show_contact_section', models.BooleanField(default=True, help_text='Show the contact section on thank you page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_you_settings', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Thank You Page Settings',
                'verbose_name_plural': 'Thank You Page Settings',
                'ordering': ['sort_order'],
            },
        ),
    ]
