# Generated by Django 5.2.6 on 2025-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_thankyoupagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankyoupagesettings',
            name='phone_link_text',
            field=models.CharField(blank=True, default='Call Us', help_text='Text for the phone link (if different from phone number)', max_length=50),
        ),
        migrations.AlterField(
            model_name='thankyoupagesettings',
            name='whatsapp_link_text',
            field=models.CharField(blank=True, default='WhatsApp Us', help_text='Text for the WhatsApp link', max_length=50),
        ),
    ]
