# Generated by Django 5.2.6 on 2025-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_thankyoupagesettings_phone_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email_sender_name',
            field=models.CharField(default='Seng Leong Website', help_text="Name displayed as the email sender (e.g., 'Seng Leong Website', 'Company Name')", max_length=100),
        ),
        migrations.AlterField(
            model_name='thankyoupagesettings',
            name='phone_link_text',
            field=models.CharField(blank=True, default='Call Us', help_text='Text for the phone link (Phone number us phone primary)', max_length=50),
        ),
        migrations.AlterField(
            model_name='thankyoupagesettings',
            name='whatsapp_link_text',
            field=models.CharField(blank=True, default='WhatsApp Us', help_text='Text for the WhatsApp link (phone URL uses whatsapp number)', max_length=50),
        ),
    ]
