# Generated by Django 5.2.6 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_email_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='shopee_button_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable the Shopee floating button'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shopee_button_text',
            field=models.CharField(blank=True, default='', help_text='Optional text to display next to the Shopee icon (leave blank for icon only)', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shopee_url',
            field=models.URLField(blank=True, default='https://shopee.com.my/', help_text='URL to your Shopee store'),
        ),
        migrations.AlterField(
            model_name='webhooksettings',
            name='zapier_webhook_url',
            field=models.URLField(blank=True, default='https://EXAMPLE.COM/', help_text='Zapier webhook URL to send form submissions to. Leave blank to disable Zapier integration.'),
        ),
    ]
